apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer-queue
  name: consumer-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer-queue
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: consumer-queue
    spec:
      containers:
        - image: pingintelligence/consumer-queue-image:latest
          name: consumer-queue
          ports:
            - containerPort: 7000
          resources: {}
      restartPolicy: Always
status: {}
